### ISSUE TITLE
[new-sysrepo] sysrepoctl issues

### ISSUE THREAD

**Issue by igortern** [sysrepo/sysrepo#1720]
Hi,

I've multiple issues with sysrepoctl (sysrepo:1.3.21, libyang 1.0.109):
1) it seems to ignore --search_path. It can't find modules referenced by "include" directive, unless they are in the current directory

2) fails to import standard models that the old sysrepoctl imports with no issues.

Attached are:
- import log. Places of note are marked with ">>>>>>"
- yang models (BBF standard)

Could you please help?

Regards,
Igor

[yang_models.tar.gz](https://github.com/sysrepo/sysrepo/files/3986997/yang_models.tar.gz)
[sysrepoctl_problem.log](https://github.com/sysrepo/sysrepo/files/3987002/sysrepoctl_problem.log)

**Comment by michalvasko** [comment]
Hi Igor,
there were some problems with `include` which may have caused both problems. So, please try it again with the latest `devel` and if something does not work, it is best if you provided a simple *sysrepoctl* command for me to execute to reproduce to problem.

Regards,
Michal

**Comment by igortern** [comment]
Thank you Michal.

I'll try and let you know.

Regards,
Igor

**Comment by igortern** [comment]
Hi Michal,

Moving to sysrepo and libyang from the latest devel didn't help. You can use models attached to the issue to reproduce.

In my setup 
- yang models are located in /home/igort/Perforce/OLT/aspen/main/external/third_party/yang-models/OB-BAA-standard-olt-adapter/yang
- sysrepo install directory is /home/igort/Perforce/OLT/aspen/main/external/build/host-sim/fs
- sysrepo repository directory is /home/igort/Perforce/OLT/aspen/main/external/build/host-sim/fs/sysrepo

1) --search-dir is ignored.
In the following command the current directory is NOT the directory where models are located. The existing included model wasn't found
cd /home/igort/Perforce/OLT/aspen/main/external/build/host-sim/third_party/yang-models && export SYSREPO_REPOSITORY_PATH=/home/igort/Perforce/OLT/aspen/main/external/build/host-sim/fs/sysrepo && LD_LIBRARY_PATH=/home/igort/Perforce/OLT/aspen/main/external/build/host-sim/fs/lib /home/igort/Perforce/OLT/aspen/main/external/build/host-sim/fs/bin/sysrepoctl --install /home/igort/Perforce/OLT/aspen/main/external/third_party/yang-models/OB-BAA-standard-olt-adapter/yang/bbf-l2-forwarding.yang --search-dir /home/igort/Perforce/OLT/aspen/main/external/third_party/yang-models/OB-BAA-standard-olt-adapter/yang --permissions 666
[ERR]: Data model "bbf-l2-forwarding-base" not found.
[ERR]: Invalid value "bbf-l2-forwarding-base" of "include".
[ERR]: Including "bbf-l2-forwarding-base" module into "bbf-l2-forwarding" failed.
[ERR]: Module "bbf-l2-forwarding" parsing failed.

2)
After that "sysrepoctl -l" executed in the direcory with yang models crashes:
igort@igort-vb-mint:10:21:12:~/Perforce/OLT/aspen/main/external$ cd /home/igort/Perforce/OLT/aspen/main/external/third_party/yang-models/OB-BAA-standard-olt-adapter/yang && export SYSREPO_REPOSITORY_PATH=/home/igort/Perforce/OLT/aspen/main/external/build/host-sim/fs/sysrepo && LD_LIBRARY_PATH=/home/igort/Perforce/OLT/aspen/main/external/build/host-sim/fs/lib /home/igort/Perforce/OLT/aspen/main/external/build/host-sim/fs/bin/sysrepoctl -l
sysrepoctl: /home/igort/Perforce/OLT/aspen/main/external/build/host-sim/third_party/sysrepo/sysrepo-1.3.21/src/lyd_mods.c:182: sr_lydmods_add_inv_data_deps: Assertion `set2->number == 1' failed.
Aborted (core dumped)

3) If start from scratch (after sr_clean, removing repository) and execute #1 above in directory with yang models, it succeeds, but the following models fail with crash similar to #2

Regards,
Igor

**Comment by michalvasko** [comment]
Hi Igor,
I am not able to reproduce this problem. My working directory is completely different than the one with the modules, I have put `bbf-l2-forwarding.yang` into a separate directory and used `-s`, and I have also set a custom `SYSREPO_REPOSITORY_PATH` but it still worked fine. Could you please tell me exactly what your directory setup is? Actually, the only missing information is where exactly do you have `bbf-l2-forwarding-base.yang`?

Regards,
Michal

**Comment by igortern** [comment]
Hi Michal,
For the purpose of this exercise all yang models are in the same directory (in archive attached to the 1st message in this thread).
I was able to reproduce today using the following steps:

1) **export SYSREPO_REPOSITORY_PATH=`pwd`/build/host-sim/fs/sysrepo**
at this point sysrepo repository doesn't exist yet
**ls /home/igort/Perforce/OLT/aspen/main/external/build/host-sim/fs/sysrepo**
ls: cannot access '/home/igort/Perforce/OLT/aspen/main/external/build/host-sim/fs/sysrepo': No such file or directory

2) **LD_LIBRARY_PATH=build/host-sim/fs/lib build/host-sim/fs/bin/sysrepoctl -i third_party/yang-models/OB-BAA-standard-olt-adapter/yang/bbf-l2-forwarding.yang -s third_party/yang-models/OB-BAA-standard-olt-adapter/yang**

This command completed without any messages whatsoever. However, the yang model was NOT added to sysrepo repository (see below)

**ls /home/igort/Perforce/OLT/aspen/main/external/build/host-sim/fs/sysrepo/yang/**
ietf-netconf@2011-06-01.yang                ietf-netconf-with-defaults@2011-06-01.yang  ietf-yang-library@2019-01-04.yang
ietf-netconf-notifications@2012-02-06.yang  ietf-origin@2018-02-14.yang

3) execute the same command as above again
**LD_LIBRARY_PATH=build/host-sim/fs/lib build/host-sim/fs/bin/sysrepoctl -i third_party/yang-models/OB-BAA-standard-olt-adapter/yang/bbf-l2-forwarding.yang -s third_party/yang-models/OB-BAA-standard-olt-adapter/yang**
[ERR]: Data model "bbf-l2-forwarding-base" not found.
[ERR]: Invalid value "bbf-l2-forwarding-base" of "include".
[ERR]: Including "bbf-l2-forwarding-base" module into "bbf-l2-forwarding" failed.
[ERR]: Module "bbf-l2-forwarding" parsing failed.
sysrepoctl error: Failed to connect (libyang error)

the model is in the search path
**ls third_party/yang-models/OB-BAA-standard-olt-adapter/yang/bbf-l2-forwarding-base.yang** 
third_party/yang-models/OB-BAA-standard-olt-adapter/yang/bbf-l2-forwarding-base.yang

Cheers,
Igor

**Comment by igortern** [comment]
Just to add: from the moment the error in step 3 above happens, something is broken in the repository. Even "sysrepoctl -l" doesn't work

**LD_LIBRARY_PATH=build/host-sim/fs/libbuild/host-sim/fs/bin/sysrepoctl -l**
[ERR]: Data model "bbf-l2-forwarding-base" not found.
[ERR]: Invalid value "bbf-l2-forwarding-base" of "include".
[ERR]: Including "bbf-l2-forwarding-base" module into "bbf-l2-forwarding" failed.
[ERR]: Module "bbf-l2-forwarding" parsing failed.
sysrepoctl error: Failed to connect (libyang error)

**Comment by michalvasko** [comment]
Hi,
nope, I still cannot reproduce this. Please, try these commands and post the output here:
```
LD_LIBRARY_PATH=build/host-sim/fs/lib build/host-sim/fs/bin/sysrepoctl -V
LD_LIBRARY_PATH=build/host-sim/fs/lib build/host-sim/fs/bin/sysrepoctl -i third_party/yang-models/OB-BAA-standard-olt-adapter/yang/bbf-l2-forwarding.yang -s third_party/yang-models/OB-BAA-standard-olt-adapter/yang -v3
LD_LIBRARY_PATH=build/host-sim/fs/lib build/host-sim/fs/bin/sysrepoctl -l -v3
```

Regards,
Michal

**Comment by igortern** [comment]
Hi Michal,

igort@igort-vb-mint:19:12:33:~/Perforce/OLT/aspen/main/external$ LD_LIBRARY_PATH=build/host-sim/fs/lib build/host-sim/fs/bin/sysrepoctl -V
sysrepocfg - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.3.21 (SO v4.1.8)

igort@igort-vb-mint:19:13:57:~/Perforce/OLT/aspen/main/external$ LD_LIBRARY_PATH=build/host-sim/fs/lib build/host-sim/fs/bin/sysrepoctl -i third_party/yang-models/OB-BAA-standard-olt-adapter/yang/bbf-l2-forwarding.yang -s third_party/yang-models/OB-BAA-standard-olt-adapter/yang -v3
[INF]: Libyang internal module "yang" was installed.
[INF]: File "ietf-yang-library@2019-01-04.yang" was installed.
[INF]: Libyang internal module "ietf-yang-library" was installed.
[INF]: File "ietf-netconf@2011-06-01.yang" was installed.
[INF]: Sysrepo internal dependency module "ietf-netconf" was installed.
[INF]: File "ietf-netconf-with-defaults@2011-06-01.yang" was installed.
[INF]: Sysrepo internal module "ietf-netconf-with-defaults" was installed.
[INF]: File "ietf-netconf-notifications@2012-02-06.yang" was installed.
[INF]: Sysrepo internal module "ietf-netconf-notifications" was installed.
[INF]: File "ietf-origin@2018-02-14.yang" was installed.
[INF]: Sysrepo internal module "ietf-origin" was installed.
[INF]: Module "bbf-l2-forwarding" scheduled for installation.

igort@igort-vb-mint:19:14:27:~/Perforce/OLT/aspen/main/external$ ls build/host-sim/fs/sysrepo/yang/
ietf-netconf@2011-06-01.yang                ietf-netconf-with-defaults@2011-06-01.yang  ietf-yang-library@2019-01-04.yang
ietf-netconf-notifications@2012-02-06.yang  ietf-origin@2018-02-14.yang

igort@igort-vb-mint:19:14:56:~/Perforce/OLT/aspen/main/external$ LD_LIBRARY_PATH=build/host-sim/fs/lib build/host-sim/fs/bin/sysrepoctl -i third_party/yang-models/OB-BAA-standard-olt-adapter/yang/bbf-l2-forwarding.yang -s third_party/yang-models/OB-BAA-standard-olt-adapter/yang -v3
[INF]: Applying scheduled changes.
[ERR]: Data model "bbf-l2-forwarding-base" not found.
[ERR]: Invalid value "bbf-l2-forwarding-base" of "include".
[ERR]: Including "bbf-l2-forwarding-base" module into "bbf-l2-forwarding" failed.
[ERR]: Module "bbf-l2-forwarding" parsing failed.
[INF]: No scheduled changes.
sysrepoctl error: Failed to connect (libyang error)

Thanks,
Igor

**Comment by igortern** [comment]
sorry, the last command was bad C&P. Removing sysrepo repository and repeating the sequence below:
igort@igort-vb-mint:19:15:32:~/Perforce/OLT/aspen/main/external$ rm -fr build/host-sim/fs/sysrepo
igort@igort-vb-mint:19:19:42:~/Perforce/OLT/aspen/main/external$ LD_LIBRARY_PATH=build/host-sim/fs/lib build/host-sim/fs/bin/sysrepoctl -V
sysrepocfg - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.3.21 (SO v4.1.8)

igort@igort-vb-mint:19:19:48:~/Perforce/OLT/aspen/main/external$ LD_LIBRARY_PATH=build/host-sim/fs/lib build/host-sim/fs/bin/sysrepoctl -i third_party/yang-models/OB-BAA-standard-olt-adapter/yang/bbf-l2-forwarding.yang -s third_party/yang-models/OB-BAA-standard-olt-adapter/yang -v3
[INF]: Libyang internal module "yang" was installed.
[INF]: File "ietf-yang-library@2019-01-04.yang" was installed.
[INF]: Libyang internal module "ietf-yang-library" was installed.
[INF]: File "ietf-netconf@2011-06-01.yang" was installed.
[INF]: Sysrepo internal dependency module "ietf-netconf" was installed.
[INF]: File "ietf-netconf-with-defaults@2011-06-01.yang" was installed.
[INF]: Sysrepo internal module "ietf-netconf-with-defaults" was installed.
[INF]: File "ietf-netconf-notifications@2012-02-06.yang" was installed.
[INF]: Sysrepo internal module "ietf-netconf-notifications" was installed.
[INF]: File "ietf-origin@2018-02-14.yang" was installed.
[INF]: Sysrepo internal module "ietf-origin" was installed.
[INF]: Module "bbf-l2-forwarding" scheduled for installation.
igort@igort-vb-mint:19:19:53:~/Perforce/OLT/aspen/main/external$ LD_LIBRARY_PATH=build/host-sim/fs/lib build/host-sim/fs/bin/sysrepoctl -l -v3
[INF]: Applying scheduled changes.
[ERR]: Data model "bbf-l2-forwarding-base" not found.
[ERR]: Invalid value "bbf-l2-forwarding-base" of "include".
[ERR]: Including "bbf-l2-forwarding-base" module into "bbf-l2-forwarding" failed.
[ERR]: Module "bbf-l2-forwarding" parsing failed.
[INF]: No scheduled changes.
sysrepoctl error: Failed to connect (libyang error)
igort@igort-vb-mint:19:20:06:~/Perforce/OLT/aspen/main/external$

**Comment by igortern** [comment]
and again without terminal hightlighting characters that made the previous post look ugly

igort@igort-vb-mint:19:15:32:~/Perforce/OLT/aspen/main/external$ rm -fr build/host-sim/fs/sysrepo
igort@igort-vb-mint:19:19:42:~/Perforce/OLT/aspen/main/external$ LD_LIBRARY_PATH=build/host-sim/fs/lib build/host-sim/fs/bin/sysrepoctl -V
sysrepocfg - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.3.21 (SO v4.1.8)

igort@igort-vb-mint:19:19:48:~/Perforce/OLT/aspen/main/external$ LD_LIBRARY_PATH=build/host-sim/fs/lib build/host-sim/fs/bin/sysrepoctl -i third_party/yang-models/OB-BAA-standard-olt-adapter/yang/bbf-l2-forwarding.yang -s third_party/yang-models/OB-BAA-standard-olt-adapter/yang -v3
[INF]: Libyang internal module "yang" was installed.
[INF]: File "ietf-yang-library@2019-01-04.yang" was installed.
[INF]: Libyang internal module "ietf-yang-library" was installed.
[INF]: File "ietf-netconf@2011-06-01.yang" was installed.
[INF]: Sysrepo internal dependency module "ietf-netconf" was installed.
[INF]: File "ietf-netconf-with-defaults@2011-06-01.yang" was installed.
[INF]: Sysrepo internal module "ietf-netconf-with-defaults" was installed.
[INF]: File "ietf-netconf-notifications@2012-02-06.yang" was installed.
[INF]: Sysrepo internal module "ietf-netconf-notifications" was installed.
[INF]: File "ietf-origin@2018-02-14.yang" was installed.
[INF]: Sysrepo internal module "ietf-origin" was installed.
[INF]: Module "bbf-l2-forwarding" scheduled for installation.
igort@igort-vb-mint:19:19:53:~/Perforce/OLT/aspen/main/external$ LD_LIBRARY_PATH=build/host-sim/fs/lib build/host-sim/fs/bin/sysrepoctl -l -v3
[INF]: Applying scheduled changes.
[ERR]: Data model "bbf-l2-forwarding-base" not found.
[ERR]: Invalid value "bbf-l2-forwarding-base" of "include".
[ERR]: Including "bbf-l2-forwarding-base" module into "bbf-l2-forwarding" failed.
[ERR]: Module "bbf-l2-forwarding" parsing failed.
[INF]: No scheduled changes.
sysrepoctl error: Failed to connect (libyang error)
igort@igort-vb-mint:19:20:06:~/Perforce/OLT/aspen/main/external$

**Comment by igortern** [comment]
Hi Michal,
sorry for many posts. Please ignore strike-through font, it magically appears after C&P from terminal screen. 
Igor

**Comment by michalvasko** [comment]
Hi Igor,
firstly, to avoid formatting problems, it is best to wrap any code/terminal output in ```. Also, you can edit your comments.

As for the issue, it is mostly my fault but any bugfixes and generally the most up-to-date version is found in the `devel` branch, not `master`, so whenever you have a problem you should first try to switch branches or always use `devel` (as mentioned [here](https://github.com/sysrepo/sysrepo#branches)). So, please do that (you should use version 1.3.29) and try again, most likely it was fixed already.

Regards,
Michal

**Comment by igortern** [comment]
Hi Michal,

Thank you for the hint re devel. I updated both sysrepo and libyang from devel and model import progressed further. However, it still fails on the 2nd problem reported in the beginning of this thread.
See "[ERR]: Failed to find matching hash" error below.
The same standard models can be imported with old sysrepo without problem.

Could you help?

Thanks,
Igor

LD_LIBRARY_PATH=/home/igort/Perforce/OLT/aspen/main/external/build/host-sim/fs/lib /home/igort/Perforce/OLT/aspen/main/external/build/host-sim/fs/bin/sysrepoctl -V3
sysrepocfg - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.3.30 (SO v4.1.17)

LD_LIBRARY_PATH=/home/igort/Perforce/OLT/aspen/main/external/build/host-sim/fs/lib /home/igort/Perforce/OLT/aspen/main/external/build/host-sim/fs/bin/sysrepoctl --install /home/igort/Perforce/OLT/aspen/main/external/third_party/yang-models/OB-BAA-standard-olt-adapter/yang/bbf-l2-forwarding.yang --search-dir /home/igort/Perforce/OLT/aspen/main/external/third_party/yang-models/OB-BAA-standard-olt-adapter/yang --permissions 666 --enable-feature forwarding-databases --enable-feature shared-forwarding-databases --enable-feature mac-learning --enable-feature split-horizon-profiles -v3
[INF]: Libyang internal module "yang" was installed.
[INF]: Libyang internal module "ietf-yang-library" was installed.
[INF]: File "ietf-netconf@2011-06-01.yang" was installed.
[INF]: Sysrepo internal dependency module "ietf-netconf" was installed.
[INF]: File "ietf-netconf-with-defaults@2011-06-01.yang" was installed.
[INF]: Sysrepo internal module "ietf-netconf-with-defaults" was installed.
[INF]: File "ietf-netconf-notifications@2012-02-06.yang" was installed.
[INF]: Sysrepo internal module "ietf-netconf-notifications" was installed.
[INF]: File "ietf-origin@2018-02-14.yang" was installed.
[INF]: Sysrepo internal module "ietf-origin" was installed.
[INF]: Module "bbf-l2-forwarding" scheduled for installation.
[INF]: File "bbf-l2-forwarding-base@2018-12-03.yang" was installed.
[INF]: File "bbf-l2-forwarding-flooding-policies@2018-12-03.yang" was installed.
[INF]: File "bbf-yang-types@2018-07-13.yang" was installed.
[INF]: File "bbf-interface-usage@2018-12-03.yang" was installed.
[INF]: File "ietf-interfaces@2018-02-20.yang" was installed.
[INF]: File "iana-if-type@2017-01-19.yang" was installed.
[INF]: File "bbf-if-type@2018-12-03.yang" was installed.
[INF]: File "bbf-frame-classification@2018-07-13.yang" was installed.
[INF]: File "bbf-dot1q-types@2018-07-13.yang" was installed.
[INF]: File "bbf-inet-types@2017-05-08.yang" was installed.
[INF]: File "bbf-l2-forwarding-forwarders@2018-12-03.yang" was installed.
[INF]: File "bbf-l2-forwarding-forwarding-databases@2018-12-03.yang" was installed.
[INF]: File "bbf-l2-forwarding-mac-learning@2018-12-03.yang" was installed.
[INF]: File "bbf-l2-forwarding-split-horizon-profiles@2018-12-03.yang" was installed.
[INF]: File "bbf-l2-forwarding-mac-learning-control@2018-12-03.yang" was installed.

LD_LIBRARY_PATH=/home/igort/Perforce/OLT/aspen/main/external/build/host-sim/fs/lib /home/igort/Perforce/OLT/aspen/main/external/build/host-sim/fs/bin/sysrepoctl --install /home/igort/Perforce/OLT/aspen/main/external/third_party/yang-models/OB-BAA-standard-olt-adapter/yang/bbf-yang-types.yang --search-dir /home/igort/Perforce/OLT/aspen/main/external/third_party/yang-models/OB-BAA-standard-olt-adapter/yang --permissions 6 -v3
[INF]: Applying scheduled changes.
[INF]: File "bbf-l2-forwarding@2018-12-03.yang" was installed.
[INF]: Module "bbf-l2-forwarding" was installed.
[INF]: Scheduled changes applied.
[INF]: Module "bbf-yang-types" scheduled for installation.

LD_LIBRARY_PATH=/home/igort/Perforce/OLT/aspen/main/external/build/host-sim/fs/lib /home/igort/Perforce/OLT/aspen/main/external/build/host-sim/fs/bin/sysrepoctl --install /home/igort/Perforce/OLT/aspen/main/external/third_party/yang-models/OB-BAA-standard-olt-adapter/yang/bbf-dot1q-types.yang --search-dir /home/igort/Perforce/OLT/aspen/main/external/third_party/yang-models/OB-BAA-standard-olt-adapter/yang --permissions 666 -v3
[INF]: Applying scheduled changes.
[ERR]: Failed to find matching hash for a child of "forwarding". (path: /bbf-l2-forwarding:forwarding)
sysrepoctl error: Failed to connect (libyang error)

LD_LIBRARY_PATH=/home/igort/Perforce/OLT/aspen/main/external/build/host-sim/fs/lib /home/igort/Perforce/OLT/aspen/main/external/build/host-sim/fs/bin/sysrepoctl -l -v3
[INF]: Applying scheduled changes.
[ERR]: Failed to find matching hash for a child of "forwarding". (path: /bbf-l2-forwarding:forwarding)
sysrepoctl error: Failed to connect (libyang error)

**Comment by michalvasko** [comment]
Hi,
I am not able to reproduce this, again. What *libyang* version are you using?

Regards,
Michal

**Comment by igortern** [comment]
Hi Michal,
I took libyang from devel at the same time as sysrepo. The build artifact
is libyang.so.1.5.8.

Noter that the problem is only reproducible when bbf-l2-forwarding.yang is
installed with --enable-feature as in my last post
... -i bbf-l2-forwarding.yang  --enable-feature forwarding-databases
--enable-feature shared-forwarding-databases --enable-feature mac-learning
--enable-feature split-horizon-profiles

Regards,
Igor

**Comment by michalvasko** [comment]
Hi Igor,
sorry about that, the commands are long, and thanks for pointing out the features. There was again a problem with submodules but it should work now and I have added a new test case.

Regards,
Michal

**Comment by igortern** [comment]
Hi Michal,

Thank you for the quick fix. Now module import process finished importing all modules, but the repository in the end of import appears to be broken. sysrepoctl -l fails with error 
[ERR]: Invalid context for LYB data parsing, missing module "bbf-ldra@2018-07-13".
sysrepoctl error: Failed to connect (libyang error)
Unfortunately I wasn't able to reproduce the problem with a small subset of modules. Attached are 2 files:
- sysrepo-module-import.log - full log including import commands with -v3
- sysrepo-module-import.sh - shell script that performs the import. The script operates on the same model bundle that is attached to the 1st post in this thread.

[sysrepo-module-import.log](https://github.com/sysrepo/sysrepo/files/4028263/sysrepo-module-import.log)
[sysrepo-module-import.sh.zip](https://github.com/sysrepo/sysrepo/files/4028269/sysrepo-module-import.sh.zip)






Regards,
Igor

**Comment by michalvasko** [comment]
Hi Igor,
I did not manage to reproduce it, attaching my log. What *libyang* version are you using? Try updating to the latest `devel`.

[out.log](https://github.com/sysrepo/sysrepo/files/4029563/out.log)

Regards,
Michal

**Comment by igortern** [comment]
Hi Michal,

I took fresh libyang and sysrepo from devel right now and still can
reproduce the problem (libyang shared library version is 1.5.10). Did you
try to import models using my script? I see some differences, for example
permission is to 600 (666 in my script).

Thanks,
Igor

**Comment by michalvasko** [comment]
Hi Igor,
I did use your script and the permissions 600 are correct. If you look at `sysrepoctl` help, you will see that `permissions` is argument only for the `change` operation, not `install`. In other words, modules are not installed immediately, only when a new connection is created and there are no other (usually the next `sysrepoctl` command as can also be seen from the output), so it is not possible to change the permission when the module is not installed yet. Hence this parameter is simply ignored, I will add checks for this.

As for the issue, what platform are you on? Did you try the script after `make sr_clean`? I am not sure what other differences there may be.

Regards,
Michal

**Comment by igortern** [comment]
Hi Michal,

You are right. I removed the repository before every test, but didn't do
sr_clean. After sr_clean the problem disappeared.

As an idea for future improvements, I suggest automatic state clean in shm
when the 1st client starts. It can be done for example using flock.
- sr_connect can 1st try to acquire exclusive flock. If successful, it
means that it is the only client and clears shm state. After that it
releases the lock and acquires shared flock on the same file.
That is, every client holds a shared lock. If process dies, locks get
released automatically, so, shm state never gets stale.

Thanks,
Igor

**Comment by michalvasko** [comment]
Hi Igor,
I do not think an automatic state clean is desired. Generally, there should always be only valid information and it should not be cleared. Exceptions are only when something goes wrong, mostly because there is a bug in *sysrepo* or in some cases in an application, or the shared memory structure changes. Then the shared memory can be cleared manually (there is actually another `make` target `shm_clean`, which should clear only the shared memory and so any persistent data are kept).

Regards,
Michal

**Comment by igortern** [comment]
Hi Michal,

make targets shm_clean, etc. are only available on the build machine. The
problems can happen on the target machine.

Thanks,
Igor

**Comment by michalvasko** [comment]
Hi,
in those cases (deployment) you should still be able to do `shm_clean` by simply restarting the machine.

Regards,
Michal
