### ISSUE TITLE
[new sysrepo] Action not working in conditional augment

### ISSUE THREAD

**Issue by gitter-runner** [sysrepo/sysrepo#1838]
Hi,
I have the following problem when I try to use action in a conditional augment. I have the following model (augment of ietf-interfaces@2018-02-20.yang):

```
module test1 {

  yang-version 1.1;
  namespace "urn:com:test";
  prefix t1;

  import iana-if-type {
    prefix iana-if-type;
  }

  import ietf-interfaces {
    prefix if;
  }

  description
    "Test model";

  revision 2020-02-25 {
    description
      "Initial version";
  }

  augment "/if:interfaces/if:interface" {
    when "if:type = 'iana-if-type:ethernetCsmacd'";
    action cond_action {
    }
  }
}
```

The startup data is the following:

```
<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
  <interface>
    <name>eth0</name>
    <description></description>
    <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type>
  </interface>
</interfaces>
```

When I try to invoke _cond_action_ on _eth0_ I get a _libyang_ error:

```
$ sysrepocfg -C startup -d running
$ application_changes_example ietf-interfaces &


 ========== READING RUNNING CONFIG: ==========

/ietf-interfaces:interfaces (container)
/ietf-interfaces:interfaces/interface[name='eth0'] (list instance)
/ietf-interfaces:interfaces/interface[name='eth0']/name = eth0
/ietf-interfaces:interfaces/interface[name='eth0']/description = 
/ietf-interfaces:interfaces/interface[name='eth0']/type = iana-if-type:ethernetCsmacd
/ietf-interfaces:interfaces/interface[name='eth0']/enabled = true [default]


 ========== LISTENING FOR CHANGES ==========

$ rpc_subscribe_example "/ietf-interfaces:interfaces/interface[name='eth0']/test1:cond_action" &
Application will subscribe to "/ietf-interfaces:interfaces/interface[name='eth0']/test1:cond_action" RPC.

========== LISTENING FOR RPC ==========

$ rpc_send_example "/ietf-interfaces:interfaces/interface[name='eth0']/test1:cond_action"
Application will send RPC "/ietf-interfaces:interfaces/interface[name='eth0']/test1:cond_action".

========== RPC "/ietf-interfaces:interfaces/interface[name='eth0']/test1:cond_action" RECEIVED: =======================

[ERR]: When condition "ietf-interfaces:type = 'iana-if-type:ethernetCsmacd'" not satisfied. (path: /ietf-interfaces:interfaces/interface[name='eth0']/test1:cond_action)
[ERR]: Action output validation failed.
```

sysrepo version: 1.4.18
libyang version: 1.0.139

Thanks!

**Comment by michalvasko** [comment]
Hi,
right, you managed to find a non-working case even though I was hoping it was fully correct already. Should be fixed now, test included.

Regards,
Michal

**Comment by GuoyouZhang** [comment]
great:)
the commit fixed the action output check!
but for action input check, it still has similar issue. i mean i have to give interface type together with the action when call the netconf action.
Thanks!

**Comment by michalvasko** [comment]
Hi,
you are doing something wrong because you do not have to put any data into the condition. In the test I [create an action](https://github.com/sysrepo/sysrepo/blob/devel/tests/test_rpc_action.c#L1168) without any other data but `condition` set to `true` [is required](https://github.com/sysrepo/sysrepo/blob/devel/tests/files/act3.yang#L52). I have it only in the operational datastore, which it is validated against. Have you checked it is there? It is not enough if the `type` is set in the running datastore.

Regards,
Michal

**Comment by gitter-runner** [comment]
Thanks for the really quick fix! Now it works on sysrepo level.
However I still get similar issue if I try to execute the action through netopeer2 server.

The netconf request:

<action xmlns="urn:ietf:params:xml:ns:yang:1">
  <interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
    <interface>
      <name>eth0</name>
      <cond_action xmlns="urn:com:test"/>
    </interface>
  </interfaces>
</action>

Response:
<?xml version="1.0" encoding="utf-8"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="9">
  <rpc-error>
    <error-type>protocol</error-type>
    <error-tag>invalid-value</error-tag>
    <error-severity>error</error-severity>
    <error-path>/ietf-interfaces:interfaces/interface[name='eth0']/test1:cond_action</error-path>
    <error-message xml:lang="en">When condition "ietf-interfaces:type = 'iana-if-type:ethernetCsmacd'" not satisfied.</error-message>
  </rpc-error>
</rpc-reply>

Netopeer2 log:
[INF]: LY: Resolving unresolved data nodes and their constraints...
[ERR]: LY: When condition "ietf-interfaces:type = 'iana-if-type:ethernetCsmacd'" not satisfied. (/ietf-interfaces:interfaces/interface[name='eth0']/test1:cond_action)
[INF]: NP: Session 1: thread 4 event bad RPC.
[INF]: NP: Session 1: thread 4 event reply error.

I figured out that the error is thrown from lyd_parse_xml() which is called by libnetconf2. 

sysrepo version: 1.4.19
libyang version: 1.0.139
libnetconf2 version: 1.1.11
netopeer2 version: 1.1.15

**Comment by michalvasko** [comment]
Hi,
right, please update *libyang* and *sysrepo*, should be working now. I have even reverted the initial bugfix because it was actually correct and the whole problem was in *libyang*.

Regards,
Michal

**Comment by gitter-runner** [comment]
Thanks again for the quick fix, I'll update and try it out!

**Comment by GuoyouZhang** [comment]
it works now, thanks!
