### ISSUE TITLE
Waiting for subscription of "XXX" failed, previous event "operational" with ID 5746 was not processed.

### ISSUE THREAD

**Issue by rydy** [sysrepo/sysrepo#2524]
Hi,
   I tried to export operational data with sysrepocfg,  Occasionally an exception occurs as shown in the following:
```
~# sysrepocfg --export --format xml --datastore operational --module XXX  -v 3
[INF]: Scheduled changes not applied because of other existing connections.
[INF]: Connection 145 created.
[INF]: Session 15662 (user "root", CID 145) created.
[ERR]: Waiting for subscription of "XXX" failed, previous event "operational" with ID 5746 was not processed.
sysrepocfg error: Getting data failed (Timeout expired)
[WRN]: Recovered a read-lock of CID 143 (sr_shmmod_lock).
```
Unable to enter the sysrepo-plugind framework callback properly, How to solve it?

Thanks.

**Comment by michalvasko** [comment]
What *sysrepo* version are you using? Did the application providing the data crash before?

**Comment by rydy** [comment]
> What _sysrepo_ version are you using? Did the application providing the data crash before?

Version 1.4.122
Yes, applications have crashed,The problem persists after restarting the system.

**Comment by michalvasko** [comment]
Try updating *sysrepo* and all the dependencies to the latest v1 releases of to the current `libyang1` branches. If that does not help, provide a way for me to reproduce it and then I can attempt to fix it.

**Comment by rydy** [comment]
> Try updating _sysrepo_ and all the dependencies to the latest v1 releases of to the current `libyang1` branches. If that does not help, provide a way for me to reproduce it and then I can attempt to fix it.

I find this problem occurs even when the application does not crash，Adding log Information  
```
# sysrepocfg --export --format xml --datastore operational --module AAA -v 3
[INF]: Scheduled changes not applied because of other existing connections.
[INF]: Connection 32 created.
[INF]: Session 5740 (user "root", CID 32) created.
[INF]: Published event "operational" "/AAA:topo-info" with ID 40.
[INF]: Event "operational" with ID 40 succeeded.
<topo-info xmlns="urn:test:topo:1.0">
  <hop>1</hop>
  <topo>0</topo>
</topo-info>
# sysrepocfg --export --format xml --datastore operational --module AAA -v 3
[INF]: Scheduled changes not applied because of other existing connections.
[INF]: Connection 33 created.
[INF]: Session 5743 (user "root", CID 33) created.
[INF]: Published event "operational" "/AAA:topo-info" with ID 41.
[INF]: Event "operational" with ID 41 succeeded.
<topo-info xmlns="urn:test:topo:1.0">
  <hop>1</hop>
  <topo>0</topo>
</topo-info>
[ERR]: Waiting on a conditional variable failed (sr_shmmod_lock: Connection timed out).
[ERR]: Module "test-energy-saving" is being used by session 5742 (NC SID 0).
# sysrepocfg --export --format xml --datastore operational --module XXX -v 3
[INF]: Scheduled changes not applied because of other existing connections.
[INF]: Connection 31 created.
[INF]: Session 5623 (user "root", CID 31) created.
[ERR]: Internal error (/home2/baocaijun/workspace/project/RRU_T3K/release/build_dir/target-arm-xilinx-linux-gnueabi/sysrepo-devel/src/common.c:3607).
[ERR]: Waiting for subscription of "XXX" failed, previous event "(null)" with ID 251 was not processed.
sysrepocfg error: Getting data failed (Timeout expired)
#
```

**Comment by michalvasko** [comment]
Based on the internal error line, I see that you have not updated anything, I do not know what version you are using exactly because it matches none that I checked. As for the issue, session 5742 is being created somewhere that is blocking access to some module. I do not see in the output so I am guessing it is in some other application.

**Comment by rydy** [comment]
I updated to the latest release (sysrepo_v1.4.140, libyang_v1.0.240), occasionally encountered the following problems.

> root@OpenWrt:~# sysrepocfg --export --format xml --datastore operational --module carrier-management  -v 3
> [INF]: Scheduled changes not applied because of other existing connections.
> [INF]: Connection 33 created.
> [INF]: Session 18409 (user "root", CID 33) created.
> [ERR]: Waiting for subscription of "carrier-management" failed, previous event "operational" with ID 5367 was not processed.
> sysrepocfg error: Getting data failed (Timeout expired)
> [ERR]: Waiting on a conditional variable failed (sr_shmmod_lock: Connection timed out).
>

**Comment by rydy** [comment]
I updated to the latest release (sysrepo_v1.4.140, libyang_v1.0.240), occasionally encountered the following problems.

> root@OpenWrt:~# sysrepocfg --export --format xml --datastore operational --module carrier-management  -v 3
> [INF]: Scheduled changes not applied because of other existing connections.
> [INF]: Connection 33 created.
> [INF]: Session 18409 (user "root", CID 33) created.
> [ERR]: Waiting for subscription of "carrier-management" failed, previous event "operational" with ID 5367 was not processed.
> sysrepocfg error: Getting data failed (Timeout expired)
> [ERR]: Waiting on a conditional variable failed (sr_shmmod_lock: Connection timed out).
> 


> Try updating _sysrepo_ and all the dependencies to the latest v1 releases of to the current `libyang1` branches. If that does not help, provide a way for me to reproduce it and then I can attempt to fix it.

I updated to the latest release (sysrepo_v1.4.140, libyang_v1.0.240), occasionally encountered the following problems.

> root@OpenWrt:~# sysrepocfg --export --format xml --datastore operational --module carrier-management  -v 3
> [INF]: Scheduled changes not applied because of other existing connections.
> [INF]: Connection 33 created.
> [INF]: Session 18409 (user "root", CID 33) created.
> [ERR]: Waiting for subscription of "carrier-management" failed, previous event "operational" with ID 5367 was not processed.
> sysrepocfg error: Getting data failed (Timeout expired)
> [ERR]: Waiting on a conditional variable failed (sr_shmmod_lock: Connection timed out).
>

**Comment by rydy** [comment]
> Try updating _sysrepo_ and all the dependencies to the latest v1 releases of to the current `libyang1` branches. If that does not help, provide a way for me to reproduce it and then I can attempt to fix it.

I updated to the latest release (sysrepo_v1.4.140, libyang_v1.0.240), occasionally encountered the following problems.

> root@OpenWrt:~# sysrepocfg --export --format xml --datastore operational --module carrier-management  -v 3
> [INF]: Scheduled changes not applied because of other existing connections.
> [INF]: Connection 33 created.
> [INF]: Session 18409 (user "root", CID 33) created.
> [ERR]: Waiting for subscription of "carrier-management" failed, previous event "operational" with ID 5367 was not processed.
> sysrepocfg error: Getting data failed (Timeout expired)
> [ERR]: Waiting on a conditional variable failed (sr_shmmod_lock: Connection timed out).
>

**Comment by michalvasko** [comment]
Based on the output, it seems some operational events time out. You can try increasing the timeout by executing *netopeer2* as `netopeer2-server -t 10`, for example.

**Comment by rydy** [comment]
I set the timeout to 30 seconds（netopeer2-server -t 30），And when that happens it's going to time out every time.

**Comment by michalvasko** [comment]
I see. Then the previous error is relevant, regarding the event with the mentioned ID. Also, I think something with these leftover events was improved in *sysrepo* v2.

**Comment by rydy** [comment]
> I see. Then the previous error is relevant, regarding the event with the mentioned ID. Also, I think something with these leftover events was improved in _sysrepo_ v2.

Is version 1 still maintained? I used the following script to test, 
```
#!/bin/sh

count=0
while true
do
        sleep 1
        sysrepocfg --export --format xml --datastore operational --module carrier-management  -v 3
        let count+=1
        echo "count: $count"
done
```
This issue will recur after running for a while.
```
root@OpenWrt:~# sysrepocfg --export --format xml --datastore operational --module carrier-management  -v 3
[WRN]: Connection with CID 564 is dead.
[INF]: Scheduled changes not applied because of other existing connections.
[INF]: Connection 565 created.
[INF]: Session 1046 (user "root", CID 565) created.
[ERR]: Internal error (/home2/yangrui/work_space/rru_4t4r_9025_7035/trunk/build_dir/target-arm-xilinx-linux-gnueabi/sysrepo-1.4.147/src/common.c:3743).
[ERR]: Waiting for subscription of "carrier-management" failed, previous event "(null)" with ID 347 was not processed.
sysrepocfg error: Getting data failed (Timeout expired)
[WRN]: Recovered a read-lock of CID 564 (sr_shmmod_lock).
root@OpenWrt:~#
```
Delete /dev/shm and return to normal.

**Comment by michalvasko** [comment]
> [WRN]: Connection with CID 564 is dead.

I would need to know the cause of this, the output you posted is just the result of some previous problem (seems like a crash). So please attach longer output and I may try to fix this.

**Comment by rydy** [comment]
I found a way to reproduce the problem.

Start by making the plugin callback processing("operational" "/carrier-management:carriers-management" event) time out(sleep 40s) every time.

Keep starting and stopping the following script.
```

#!/bin/sh

count=0
while true
do
        sysrepocfg --export --format xml --datastore operational --module carrier-management  -v 3
        let count+=1
        echo "count: $count"
done

```

It is normal for the following log to appear.

```
[INF]: Scheduled changes not applied because of other existing connections.
[INF]: Connection 2 created.
[INF]: Session 2 (user "root", CID 2) created.
[INF]: Published event "operational" "/carrier-management:carriers-management" with ID 1.
[ERR]: Callback event "operational" with ID 1 processing timed out.
[WRN]: Event "operational" with ID 1 failed (Timeout expired).
sysrepocfg error: Getting data failed (User callback failed)
count: 1
```

The following log is abnormal. Unable to enter callback("operational" "/carrier-management:carriers-management" event) processing.

```
[WRN]: Connection with CID 22 is dead.
[INF]: Scheduled changes not applied because of other existing connections.
[INF]: Connection 23 created.
[INF]: Session 30 (user "root", CID 23) created.
[ERR]: Internal error (/home2/yangrui/work_space/rru_4t4r_9025_7035/trunk/build_dir/target-arm-xilinx-linux-gnueabi/sysrepo-1.4.147/src/common.c:3743).
[ERR]: Waiting for subscription of "carrier-management" failed, previous event "(null)" with ID 21 was not processed.
sysrepocfg error: Getting data failed (Timeout expired)
[WRN]: Recovered a read-lock of CID 22 (sr_shmmod_lock).
count: 1
[INF]: Scheduled changes not applied because of other existing connections.
[INF]: Connection 24 created.
[INF]: Session 31 (user "root", CID 24) created.
[ERR]: Internal error (/home2/yangrui/work_space/rru_4t4r_9025_7035/trunk/build_dir/target-arm-xilinx-linux-gnueabi/sysrepo-1.4.147/src/common.c:3743).
[ERR]: Waiting for subscription of "carrier-management" failed, previous event "(null)" with ID 21 was not processed.
sysrepocfg error: Getting data failed (Timeout expired)
```

**Comment by michalvasko** [comment]
Hm, I am not sure it makes sense to debug this. At the very least, you should try it with the latest *sysrepo* v1 version (1.4.140 or even 1.4.147). Still, I think I was changing this code for *sysrepo* v2 and best thing to do is to switch using it, anyway.

**Comment by rydy** [comment]
I'm using the latest version(1.4.147), I think this is an anomaly(Unable to enter 'sysrepo' callback),  Too many changes are made in the V2 version, The upgrade is not compatible with the previous code.

**Comment by michalvasko** [comment]
Fine, since the problem was present even in *sysrepo* v2, it should now be fixed in both latest v1 and v2.

**Comment by rydy** [comment]
> Fine, since the problem was present even in _sysrepo_ v2, it should now be fixed in both latest v1 and v2.

Ok, I am testing after the update.

**Comment by rydy** [comment]
> Fine, since the problem was present even in _sysrepo_ v2, it should now be fixed in both latest v1 and v2.

Ok, I am testing after the update.

**Comment by rydy** [comment]
The problem has not recur,  Thank you for your help.

**Comment by rydy** [comment]
The problem still exists, but the probability of recurrence is low.

log:
```
root@OpenWrt:~# tail -f /tmp/log/netopeer2-server.log 
[INF]: SR: Published event "done" "o-ran-system-time" with ID 125 priority 0 for 1 subscribers.
[INF]: SR: Successful processing of "rpc" event with ID 125 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 125 priority 0 succeeded.
[INF]: NP: Session 188: thread 4 event new RPC.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" "/ietf-netconf:get" with ID 930 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:get" "rpc" event with ID 930 priority 0 (remaining 1 subscribers).


[ERR]: SR: Internal error (/home2/baocaijun/workspace/project/RRU_T3K/release/build_dir/target-arm-xilinx-linux-gnueabi/sysrepo-1.4.148/src/common.c:3736).
[ERR]: SR: Waiting for subscription of "interfaces-cpri-topo" failed, previous event "(null)" with ID 1 was not processed.
[ERR]: NP: Getting data "/interfaces-cpri-topo:*" from sysrepo failed (Timeout expired).
[INF]: SR: Failed processing of "rpc" event with ID 930 priority 0 (remaining 1 subscribers).
[ERR]: SR: Waiting for subscription of "interfaces-cpri-topo" failed, previous event "(null)" with ID 1 was not processed.
[WRN]: SR: Event "rpc" with ID 930 priority 0 failed (Timeout expired).
[ERR]: NP: Failed to send an RPC (User callback failed).
[INF]: NP: Session 188: thread 2 event new RPC.
[INF]: NP: Session 188: thread 2 event reply error.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" "/ietf-netconf:get" with ID 931 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:get" "rpc" event with ID 931 priority 0 (remaining 1 subscribers).
```
