### ISSUE TITLE
Segfault in sr_edit_batch

### ISSUE THREAD

**Issue by syyyr** [sysrepo/sysrepo#2661]
Hi, this program is supposed create push-style operational data, and then remove it again:
```cpp
#include <iostream>
#include <sysrepo.h>
#include <string>

int main(int argc, char* argv[])
{
    sr_log_stderr(SR_LL_INF);
    sr_conn_ctx_t* conn = nullptr;
    sr_connect(0, &conn);
    sr_session_ctx_t* sess = nullptr;
    sr_session_start(conn, SR_DS_RUNNING, &sess);

    sr_session_switch_ds(sess, SR_DS_OPERATIONAL);
    auto ctx = sr_session_acquire_context(sess);
    lyd_node* node;
    lyd_new_path(nullptr, ctx, "/test_module:stateLeaf", "123", 0, &node);
    sr_edit_batch(sess, node, "merge");
    sr_apply_changes(sess, 0);
    lyd_free_all(node);

    lyd_new_path(nullptr, ctx, "/test_module:stateLeaf", nullptr, LYD_NEW_PATH_OPAQ, &node);
    lyd_new_attr(node, "ietf-netconf", "ietf-netconf:operation", "remove", nullptr);
    sr_edit_batch(sess, node, "merge");
    lyd_free_all(node);
    sr_apply_changes(sess, 0);

    sr_session_release_context(sess);
    sr_session_stop(sess);
    sr_disconnect(conn);

    return 0;
}

}
```
I have two problems with this:
1) It causes a segfault:

```
$ ./a.out 
[INF] Connection 46 created.
[INF] Session 16 (user "vk", CID 46) created.
[WRN] Connection with CID 45 is dead.
[WRN] Recovered a read-lock of CID 45 (sr_shmmod_lock).
[WRN] Recovered a read-upgr-lock of CID 45 (sr_shmmod_lock).
[INF] No datastore changes to apply.
/home/vk/git/netconf-cli/submodules/dependencies/libyang/src/tree_data.c:3844:61: runtime error: member access within null pointer of type 'const struct lysc_node'
AddressSanitizer:DEADLYSIGNAL
=================================================================
==587932==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000010 (pc 0x7fd8bf8af7b3 bp 0x7fff78e4b070 sp 0x7fff78e4af40 T0)
==587932==The signal is caused by a READ memory access.
==587932==Hint: address points to the zero page.
    #0 0x7fd8bf8af7b3 in lyd_merge /home/vk/git/netconf-cli/submodules/dependencies/libyang/src/tree_data.c:3844
    #1 0x7fd8bf8b0e93 in lyd_merge_module /home/vk/git/netconf-cli/submodules/dependencies/libyang/src/tree_data.c:3895
    #2 0x7fd8c010a92c in sr_modinfo_edit_apply /home/vk/git/netconf-cli/submodules/dependencies/sysrepo/src/modinfo.c:373
    #3 0x7fd8c00915bf in sr_apply_changes /home/vk/git/netconf-cli/submodules/dependencies/sysrepo/src/sysrepo.c:3398
    #4 0x55cf73d89692 in main /home/vk/yang/delete_batch_oper.cpp:25
    #5 0x7fd8be629b24 in __libc_start_main (/usr/lib/libc.so.6+0x27b24)
    #6 0x55cf73d891ed in _start (/home/vk/yang/a.out+0x21ed)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/vk/git/netconf-cli/submodules/dependencies/libyang/src/tree_data.c:3844 in lyd_merge
==587932==ABORTING
```
2) It uses the netconf "remove" operation, which seems supported, but previous iteration of sysrepo also allowed "delete" and that seems to not be supported anymore. I think having the "delete" operation gives extra safety (you're not removing something that really isn't there). Could sysrepo support the "delete" operation again?

**Comment by michalvasko** [comment]
Okay, I will once again have to explain what `push` oper data do exactly and explain what is happening, I have made only minor fixes to *libyang* and *sysrepo*.

> this program is supposed create push-style operational data, and then remove it again:

That is actually not what your program is doing, you remove (revert) some stored push operational data using `sr_discard_oper_changes()`. On your first `sr_apply_changes()` you are telling *sysrepo* to "merge stateLeaf to enabled `running` data when creating `operational` datastore". On the next apply changes, what you in effect do is "remove stateLeaf from enabled `running` data if present when creating `operational` datastore" ovewriting the previous change since they are not compatible with each other. If you want to get to the state of having no push oper data being applied to enabled `running` data, call the aforementioned function.

As for the bullets:

1. SEGFAULT is fixed in *libyang* but I have also added a check for opaque data to *sysrepo*, which are actually forbidden. The reason for this is connected to what I have just written. When you set push oper data to "remove a leaf" and there is an oper module change subscriber, this change needs to be reported. For performance reasons, this change is taken as it is (an edit) and the change reported directly. But if you use an opaque node without a value, what value is supposed to be reported for the subscriber? It is missing and there is no way to get it if we do not want to be parsing `running` data and checking what actual value is there. There is another reason why the value is required and that being that the base `running` data can change so the actual deleted value could be changed.

2. No operations that can fail to be applied and cause an error are supported. Reason being that the push oper data may be possible to apply on some base `running` data but these data can later change, which would probably result in an error. So, you would, in effect, be prevented from making `running` datastore change because of some stored push oper data. I do not consider this desirable.

Finally, as you can see, `operational` data are really complex. After last changes this is the resulting overall design that fixed the problems I was trying to fix at the time. We can discuss possible improvements with regard to anything I have just mentioned but you need to be aware that even fairly simple changes often have far-reaching consequences.

**Comment by jktjkt** [comment]
Another question -- do I need to invoke `sr_apply_changes()` for `sr_discard_oper_changes()` to be visible to other connections? This is currently not documented. If this is applied immediately, then that would mean that I cannot propagate my change atomically.

**Comment by syyyr** [comment]
Btw I can confirm, that the segfault is fixed.

**Comment by syyyr** [comment]
>Another question -- do I need to invoke sr_apply_changes() for sr_discard_oper_changes() to be visible to other connections? This is currently not documented. If this is applied immediately, then that would mean that I cannot propagate my change atomically.



I have tested this:
```cpp
#include <iostream>
#include <sysrepo.h>
#include <string>

int main(int argc, char* argv[])
{
    sr_log_stderr(SR_LL_INF);
    sr_conn_ctx_t* conn = nullptr;
    sr_connect(0, &conn);
    sr_session_ctx_t* sess = nullptr;
    sr_session_start(conn, SR_DS_RUNNING, &sess);

    sr_session_switch_ds(sess, SR_DS_OPERATIONAL);
    auto ctx = sr_session_acquire_context(sess);
    lyd_node* node;
    lyd_new_path(nullptr, ctx, "/test_module:stateLeaf", "123", 0, &node);
    sr_edit_batch(sess, node, "merge");
    sr_apply_changes(sess, 0);
    lyd_free_all(node);

    sr_val_t* val;
    sr_get_item(sess, "/test_module:stateLeaf", 0, &val);
    std::cerr << "/test_module:stateLeaf = " << val->data.int32_val << "\n";
    sr_free_val(val);
    node = nullptr;

    sr_discard_oper_changes(conn, sess, "/test_module:stateLeaf", 0);
    // sr_apply_changes not needed here

    sr_get_item(sess, "/test_module:stateLeaf", 0, &val);
    if (val) {
        std::cerr << "/test_module:stateLeaf = " << val->data.int32_val << "\n";
        sr_free_val(val);
    } else {
        std::cerr << "/test_module:stateLeaf = " << "{empty}" << "\n";
    }

    sr_session_release_context(sess);
    sr_session_stop(sess);
    sr_disconnect(conn);

    return 0;
}
```
`sr_apply_changes` is not needed. It does make sense, since `sr_discard_oper_changes` takes a connection as an argument, and `sr_apply_changes` takes a session as an argument. I have already asked on Slack, but: why is push oper data tied to a connection rather than to a session?

**Comment by michalvasko** [comment]
The docs were improved a bit and all the crucial information should now be there.

> Do I understand you correctly that what I'm pushing to ops datastore is actually interpreted as "a diff" behind the scenes by sysrepo? That is, I'm instructing sysrepo how to transform the content of running and ops pull data by my pushed diff, and the content of the ops tree is built on-demand from these sources?

In general, yes, but note that it is not stored as a `diff` but as an `edit`, these terms are strictly distinguished internally in *sysrepo* although you probably did not know that and meant edit. In any case, edit behaves exactly as the content in `<edit-config>` RPC does except it supports more operations. Based on this the exact behavior should be known but I will react further just in case.

> how do I push an update which removes a leaf that is present in running?

You call `sr_oper_delete_item_str()`, which is mentioned in docs of `sr_delete_item()`, which should be the first function that comes to mind.

> what happens when my list has a config: false container, I've pushed some data for this container for a list instance which exists in the running, and then running changes and the list instance is no longer present? Do I have to push an update? Which one, presumably the sr_discard_oper_changes for the XPath in question?

It will continue to work and the container/list instance be present in `operational`. This is a direct consequence of how edit is applied so I would hope it does not need to be explicitly mentioned even though I understand that we are generally talking about quite complex mechanisms.

> how do I "remove a part of the diff" that I pushed before? discard function again, perhaps?

Yes, that is now explicitly mentioned in the docs.

> I have already asked on Slack, but: why is push oper data tied to a connection rather than to a session?

And I have answered but I did not remember the exact reason. But now I think I do, it likely is connected to the implemented data recovery mechanisms. Specifically, they are all tied to connections and it is possible to detect only crashed connections.

**Comment by jktjkt** [comment]
> > how do I push an update which removes a leaf that is present in running?
> 
> You call `sr_oper_delete_item_str()`, which is mentioned in docs of `sr_delete_item()`, which should be the first function that comes to mind.

Can I use `sr_edit_batch` for this? So far, we've used this as an "entry point" for all such modifications, and it's a very convenient API -- it allows us to see all the changes in just one place, etc.

> > what happens when my list has a config: false container, I've pushed some data for this container for a list instance which exists in the running, and then running changes and the list instance is no longer present? Do I have to push an update? Which one, presumably the sr_discard_oper_changes for the XPath in question?
> 
> It will continue to work and the container/list instance be present in `operational`. This is a direct consequence of how edit is applied so I would hope it does not need to be explicitly mentioned even though I understand that we are generally talking about quite complex mechanisms.

Yeah, it's something that our code is doing. Is it possible to express this use case (remove something which I ops-pushed before) as an argument to `sr_edit_batch`?

I'm concerned about atomicity of these operations here, BTW. I do not mind too much if I have to call several API functions for this (that's annoying, but doable, but still I would prefer just passing one libyang data tree around with all the required operations, perhaps with some magic attributes for "remove these if they are present in `running`" and other magic attributes for "remove this past change I pushed").

Also, can I call `sr_discard_oper_changes` from my `sr_module_change_cb` handler (for `EV_DONE`)?

**Comment by michalvasko** [comment]
Yes, `sr_edit_batch()` can be used instead of all the edit functions, all they do is just construct the edit passed to `sr_edit_batch()` internally.

It seems you still do not understand some thing fully and are over-complicating them, I will try to explain.

> Is it possible to express this use case (remove something which I ops-pushed before) ...

I think we are focusing too much on this use-case because it is not really interesting. Simply, the principle of incompatible push oper changes replacing one another is being used. In other words and exactly how it works internally, all the push oper changes are stored in a single edit so if there is some and you want to store another, they must be merged. All we are discussing are the rules for this merge of 2 edits.

> "remove these if they are present in running"

Again, think of this in terms of an edit. You have an edit that has `remove` operation on a leaf, which is exactly this. If this node does not exist (base data are subscribed running data), it is removed, otherwise nothing happens.

> "remove this past change I pushed"

Now this is a special use case of **directly modifying the stored edit** and that is exactly there is a dedicated function. All the other functionality we were discussing was **indirectly modifying the stored edit** in order to change the final data. The difference is obvious when I mention what exactly is happening internally. In the latter case, the edit is being changed with `lyd_new_path()` or merged using special rules. In the former case, `lyd_find_xpath()` is simply called on the edit and all matching nodes freed.

**Comment by michalvasko** [comment]
Firstly, when a node has `merge` operation and you update the edit with the same node having `delete` operation (which is what you described), you should get an error because these 2 operations cannot be merged (they cancel each other) and it is expected it is not what you want to do in a standard edit. But it is true that UPDATE callbacks are different and it does make sense there so I may add this functionality if needed. Otherwise you could always use the ISOLATE flag for the edit but like you mentioned later, this will probably result in a redundant edit node.

But to answer your question, no. If the connection that sent the changes is disconnected, its data are removed just like any other push oper data.

As for using `sr_discard_oper_changes()`, using it may have different results than what you would expect. That function always operates on the **stored** push oper edit (that is also why you do not call `sr_apply_changes()` for it) and not in the **currently processed** one that you get in an UPDATE callback. As mentioned before, having lots of changes in the push oper edit is certain to impact performance some way so best to avoid it.

We did not really get into details when discussing this design and it seems the auto-deletion of push oper data without owner may cause some problems. I am missing some information but my advice would be to either keep the connection of the originator of the changes (not sure how often they will be pushed but I keep repeating that creating a connection is quite an expensive operation) or make sure that the final stored push oper data are owned by some long-lasting connection. However, the latter solution generally disassociates the actual app that has the operational state from the stored oper push data, which basically works around that feature and hence may not be compliant to YANG operational datastore principles and its intended purpose.
